server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test_gestion?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: subte147
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
auth:
  app:
    jwtCookieName: auth
    jwtSecret: ${SecretKey}
    jwtExpirationMs: 96400000
    jwtRefresh: 2592000000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
